# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Hydrological processing model.py
# Created on: 2023-07-24 04:57:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: Hydrological processing model <Input_surface_raster> <Default_gdb> <Extent> <Cell_Size> <output_raster> <Output_accumulation_raster> <SQL_Expression> <HydroNetwork> <StreamLinks> <Streamlines> 
# Description: 
# Creates a hydrographic network from a DEM based on a minimum area threshold
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_surface_raster = arcpy.GetParameterAsText(0)

Default_gdb = arcpy.GetParameterAsText(1)
if Default_gdb == '#' or not Default_gdb:
    Default_gdb = "C:\\Users\\OceeDITT\\Documents\\ArcGIS\\Default.gdb" # provide a default value if unspecified

Extent = arcpy.GetParameterAsText(2)

Cell_Size = arcpy.GetParameterAsText(3)
if Cell_Size == '#' or not Cell_Size:
    Cell_Size = "MAXOF" # provide a default value if unspecified

output_raster = arcpy.GetParameterAsText(4)
if output_raster == '#' or not output_raster:
    output_raster = "C:\\Users\\OceeDITT\\Documents\\Geospatial Analysis\\SIWES\\Hydrological Processing Model\\Model builder data\\ModelBuilderData.gdb\\output_raster" # provide a default value if unspecified

Output_accumulation_raster = arcpy.GetParameterAsText(5)
if Output_accumulation_raster == '#' or not Output_accumulation_raster:
    Output_accumulation_raster = "C:\\Users\\OceeDITT\\Documents\\ArcGIS\\Default.gdb\\FlowAcc_outp1" # provide a default value if unspecified

SQL_Expression = arcpy.GetParameterAsText(6)
if SQL_Expression == '#' or not SQL_Expression:
    SQL_Expression = "VALUE < 100" # provide a default value if unspecified

HydroNetwork = arcpy.GetParameterAsText(7)
if HydroNetwork == '#' or not HydroNetwork:
    HydroNetwork = "C:\\Users\\OceeDITT\\Documents\\Geospatial Analysis\\SIWES\\Hydrological Processing Model\\Model builder data\\ModelBuilderData.gdb\\Setnull_flow_1" # provide a default value if unspecified

StreamLinks = arcpy.GetParameterAsText(8)
if StreamLinks == '#' or not StreamLinks:
    StreamLinks = "C:\\Users\\OceeDITT\\Documents\\Geospatial Analysis\\SIWES\\Hydrological Processing Model\\Model builder data\\ModelBuilderData.gdb\\streamlink" # provide a default value if unspecified

Streamlines = arcpy.GetParameterAsText(9)
if Streamlines == '#' or not Streamlines:
    Streamlines = "C:\\Users\\OceeDITT\\Documents\\Geospatial Analysis\\SIWES\\Hydrological Processing Model\\Model builder data\\ModelBuilderData.gdb\\streamline_feature" # provide a default value if unspecified

# Local variables:
Output_drop_raster = ""

# Process: Flow Direction
tempEnvironment0 = arcpy.env.extent
arcpy.env.extent = Extent
tempEnvironment1 = arcpy.env.cellSize
arcpy.env.cellSize = Cell Size
tempEnvironment2 = arcpy.env.workspace
arcpy.env.workspace = Default.gdb
arcpy.gp.FlowDirection_sa(Input_surface_raster, output_raster, "NORMAL", Output_drop_raster, "D8")
arcpy.env.extent = tempEnvironment0
arcpy.env.cellSize = tempEnvironment1
arcpy.env.workspace = tempEnvironment2

# Process: Flow Accumulation
arcpy.gp.FlowAccumulation_sa(output_raster, Output_accumulation_raster, "", "FLOAT", "D8")

# Process: Set Null
arcpy.gp.SetNull_sa(Output_accumulation_raster, Output_accumulation_raster, HydroNetwork, SQL_Expression)

# Process: Stream Link
arcpy.gp.StreamLink_sa(HydroNetwork, output_raster, StreamLinks)

# Process: Stream to Feature
arcpy.gp.StreamToFeature_sa(StreamLinks, output_raster, Streamlines, "SIMPLIFY")

